apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"
  - "./secrets.yaml"
patchesStrategicMerge:
  - "./deployment.yaml"
  - "./webhook-forwarder-user-config.yaml"
