apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-forwarder
  namespace: webhook-forwarder
  labels:
    app: webhook-forwarder
spec:
  replicas: 1
  template:
    metadata:
      name: webhook-forwarder
      labels:
        app: webhook-forwarder
    spec:
      serviceAccountName: webhook-forwarder-service-account
      containers:
        - name: webhook-forwarder
          env:
            - name: STATIC_CLIENTS_MODE
              value: "false"
            - name: TARGET_SERVICE_NAME
              value: _set_with_kustomize_
            - name: WEBHOOK_DESTINATION_ENDPOINT
              value: _set_with_kustomize_
            - name: HEADERS_TO_FORWARD
              value: _set_with_kustomize_
            - name: IGNORE_DESTINATION_SSL_ERRORS
              value: "false"
            - name: LOG_LEVEL
              value: "info"
          image: ghcr.io/bartosz347/webhook-forwarder:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always
  selector:
    matchLabels:
      app: webhook-forwarder
