apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-forwarder-service-account
  namespace: webhook-forwarder

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-services-access-role
  namespace: webhook-forwarder
rules:
  - apiGroups:
      - ""
      - networking.k8s.io
    resources:
      - services
      - ingresses
    verbs: [ "get", "list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-cluster-role-binding
subjects:
  - namespace: webhook-forwarder
    kind: ServiceAccount
    name: webhook-forwarder-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-services-access-role
