name: Build image

on:
  push:
    branches: [ master ]

jobs:
  test:
    uses: bartosz347/webhook-forwarder/.github/workflows/test.yml@master

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        # Extract branch name, replace `/` with `-`
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr / -)"
        id: extract_branch

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: true
          tags: |
            ghcr.io/${{ github.repository }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

